services:
 
  mongodb:
    image: mongo:4.4
    container_name: smart-task-mongodb
    ports:
      - "27017:27017"
 
  auth-service:
    image: anupriyathavasiraj/smart-task-auth-service:latest
    container_name: smart-task-auth-service
    ports:
      - "5001:5001"
    environment:
      MONGO_URI: mongodb://mongodb:27017/authdb
      JWT_SECRET: Change_me
 
  task-service:
    image: anupriyathavasiraj/smart-task-task-service:latest
    container_name: smart-task-task-service
    ports:
      - "5002:5002"
    environment:
      MONGO_URI: mongodb://mongodb:27017/taskdb
      JWT_SECRET: Change_me
 
  notification-service:
    image: anupriyathavasiraj/smart-task-notification-service:latest
    container_name: smart-task-notification-service
    ports:
      - "5003:5003"
    environment:
      MONGO_URI: mongodb://mongodb:27017/notificationdb
      JWT_SECRET: Change_me
 
  report-service:
    image: anupriyathavasiraj/smart-task-report-service:latest
    container_name: smart-task-report-service
    ports:
      - "5004:5004"
    environment:
      MONGO_URI: mongodb://mongodb:27017/reportdb
      JWT_SECRET: Change_me
 
  api-gateway:
    image: anupriyathavasiraj/smart-task-api-gateway:latest
    container_name: smart-task-api-gateway
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      AUTH_SERVICE_URL: http://auth-service:5001
      TASK_SERVICE_URL: http://task-service:5002
      JWT_SECRET: Change_me

  frontend:
    image: anupriyathavasiraj/frontend-smart-task:latest
    container_name: smart-task-frontend
    ports:
      - "8081:80"
    depends_on:
      - api-gateway  
